import json
from scripts.run_web_mandate import finish_run

ctx = {
    "run_id": "79b168bc-e343-4e30-9283-ba05d45ad4d9",
    "theme": "Find startups that use AI for battery materials and chemistry, including cathode and anode material discovery, electrolyte and additive design, and cell and module design. Focus on companies where AI drives materials discovery and design, not battery manufacturing or battery management software.",
    "geography": "Global",
    "stage": "Series A, Series B, Seed, Pre-seed",
    "search_mode": "DEEP",
    "special_instructions": "",
    "submitted_by_email": "em@icoscapital.com",
    "submitted_by_name": "Eszter Madai",
    "additional_companies": [],
    "extra_check_sites": [],
    "icos_fit": False,
    "seed_companies": [],
    "exhaustive": False,
    "include_small": True,
    "slug": "2026-09-14-find-startups-that-use-ai-for--dxloao",
    "current_round": 1,
    "watch": False,
    "t_start": 1789382745.7588694,
}

companies = [
    {
        "name": "Mitra Chem",
        "description": "AI-enabled discovery and design of iron-based (LFP/LMFP) cathode active materials for lithium-ion batteries; backed by GM.",
        "website": "mitrachem.com",
        "linkedin": "",
        "stage": "Series A",
        "geography": "USA",
        "segment": "Cathode/anode materials discovery",
        "score": None,
        "source": "Open web; X/Twitter",
        "notes": "FTE: 51-200 | Pre-screen: Pass | Traction unverified | Investors incl. GM, Social Capital, Fontinalis Partners",
    },
    {
        "name": "Ni-Cat",
        "description": "Developer of cathode active materials for batteries through an artificial-intelligence-aided process, running a prototype reactor farm for real-time, scalable production.",
        "website": "nicat.co",
        "linkedin": "",
        "stage": "Unknown",
        "geography": "Unknown",
        "segment": "Cathode/anode materials discovery",
        "score": None,
        "source": "Pipedrive CRM",
        "notes": "Pipedrive: Lost — Does not fit fund (ICF 4) strategy (2024-03-28) | Pre-screen: Pass",
    },
    {
        "name": "3DC Inc.",
        "description": "Advanced carbon materials for battery anodes/cathodes using computational/AI-driven design; targets higher-capacity, longer-life battery materials.",
        "website": "3dc.co.jp",
        "linkedin": "",
        "stage": "Unknown",
        "geography": "Japan",
        "segment": "Cathode/anode materials discovery",
        "score": None,
        "source": "VC portfolio (UntroD Capital)",
        "notes": "Pre-screen: Pass | Traction unverified",
    },
    {
        "name": "Wildcat Discovery Technologies",
        "description": "High-throughput, data-driven materials discovery platform for battery cathode/electrolyte development; acquired by Holyvolt (Sweden) for ~€63.1M in 2026.",
        "website": "wildcatdiscovery.com",
        "linkedin": "",
        "stage": "Acquired / Growth (via Holyvolt)",
        "geography": "USA",
        "segment": "Cathode/anode materials discovery",
        "score": None,
        "source": "LinkedIn; EU grants (Holyvolt acquisition news)",
        "notes": "Pre-screen: Fail — too late stage (acquired into Holyvolt's growth-stage platform, no longer an independent Seed-Series B raise)",
    },
    {
        "name": "Holyvolt",
        "description": "Swedish battery-materials R&D and discovery platform; acquired Wildcat Discovery Technologies for ~€63.1M to build out AI-driven materials discovery capability.",
        "website": "holyvolt.com",
        "linkedin": "",
        "stage": "Growth (€12-20M rounds, 2026)",
        "geography": "Sweden",
        "segment": "Cathode/anode materials discovery",
        "score": None,
        "source": "EU grants/CORDIS search",
        "notes": "Pre-screen: Fail — too late stage (Growth round, beyond Series B)",
    },
    {
        "name": "Anthro Energy",
        "description": "AI-driven electrolyte and solid-state battery materials discovery; its 'Anthro Atlas' physics-informed ML platform screens billions of candidate chemistries, compressing electrolyte development from ~6 months to hours.",
        "website": "anthroenergy.com",
        "linkedin": "",
        "stage": "Unknown (early-stage)",
        "geography": "USA",
        "segment": "Electrolyte & additive design",
        "score": None,
        "source": "VC portfolio (Voyager Ventures)",
        "notes": "Pre-screen: Pass | Traction unverified | Strong on-thesis match",
    },
    {
        "name": "Aionics",
        "description": "Artificial Molecular Intelligence (AMI) platform using generative AI for autonomous electrolyte formulation screening and design.",
        "website": "aionics.com",
        "linkedin": "",
        "stage": "Unknown",
        "geography": "USA",
        "segment": "Electrolyte & additive design",
        "score": None,
        "source": "Open web",
        "notes": "Pre-screen: Pass | Traction unverified | Named partners/customers reported: Porsche (Cellforce), Form Energy, Resonac, Cuberg",
    },
    {
        "name": "Qkera",
        "description": "AI-optimized ceramic solid electrolyte synthesis; TUM/MIT spinoff (2024) currently in industrial validation.",
        "website": "qkera.com",
        "linkedin": "",
        "stage": "Seed",
        "geography": "Germany",
        "segment": "Electrolyte & additive design",
        "score": None,
        "source": "Non-English EU search",
        "notes": "Pre-screen: Pass | Investors incl. InnoEnergy, UnternehmerTUM Funding",
    },
    {
        "name": "Chemix",
        "description": "Generative-AI-powered battery chemistry and materials design platform; claims ~10x faster battery development via AI acceleration, cobalt-free/low-nickel chemistries.",
        "website": "chemix.ai",
        "linkedin": "linkedin.com/company/chemix-inc",
        "stage": "Series A",
        "geography": "USA",
        "segment": "Battery chemistry / cell design AI",
        "score": None,
        "source": "VC portfolio (Porsche Ventures); LinkedIn",
        "notes": "Pre-screen: Pass",
    },
    {
        "name": "Polaron",
        "description": "Generative ML platform for battery and clean-energy materials design (automates microscopy/materials characterization); Imperial College London spinout, reported ~10% energy-density improvement in battery cathodes.",
        "website": "polaron.ai",
        "linkedin": "",
        "stage": "Series A ($8M, Feb 2026)",
        "geography": "United Kingdom",
        "segment": "Battery chemistry / cell design AI",
        "score": None,
        "source": "Open web; university tech-transfer search",
        "notes": "Pre-screen: Pass | Investors: Speedinvest, Racine2, Futurepresent",
    },
    {
        "name": "SES AI",
        "description": "Molecular Universe AI platform for lithium-metal battery electrolyte and materials discovery; publicly traded (NYSE: SES).",
        "website": "sesai.com",
        "linkedin": "",
        "stage": "Public (NYSE: SES)",
        "geography": "USA",
        "segment": "Battery chemistry / cell design AI",
        "score": None,
        "source": "Open web; LinkedIn",
        "notes": "Pre-screen: Fail — too late stage (publicly traded)",
    },
    {
        "name": "Citrine Informatics",
        "description": "AI/ML materials informatics platform used for accelerating discovery of battery cathode, anode, electrolyte and additive materials (also serves other materials sectors).",
        "website": "citrine.io",
        "linkedin": "",
        "stage": "Series C",
        "geography": "USA",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Herb memory; Crunchbase",
        "notes": "Pre-screen: Fail — too late stage (Series C, outside Seed-Series B)",
    },
    {
        "name": "Orbital Industries (Orbital Materials)",
        "description": "AI materials discovery company (language-to-structure 'Linus' model) applied to batteries, semiconductors and data-center cooling materials.",
        "website": "orbitalindustries.com",
        "linkedin": "",
        "stage": "Series B ($50M, May 2026)",
        "geography": "United Kingdom",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Press (TechCrunch); co-investor snowball",
        "notes": "Pre-screen: Pass | Investors: Radical Ventures, Toyota Ventures | Multi-sector (batteries is one of several target verticals)",
    },
    {
        "name": "CuspAI",
        "description": "Generative AI materials discovery platform (MIRA) combining computational simulation and experimental validation; targets batteries, semiconductors and clean energy materials. Founded 2024.",
        "website": "cusp.ai",
        "linkedin": "",
        "stage": "Series B ($450M, Jul 2026)",
        "geography": "United Kingdom",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Press (Sifted); EU grants search",
        "notes": "Pipedrive: org-only, no deal record | Pre-screen: Pass | Investors: Kleiner Perkins, NEA, Bezos Expeditions | Multi-sector, very large round for stage",
    },
    {
        "name": "ExoMatter",
        "description": "AI-enriched data platform for materials R&D screening, applicable to battery and advanced materials development. 2025 Innovation Radar Prize overall winner.",
        "website": "exomatter.ai",
        "linkedin": "",
        "stage": "Seed",
        "geography": "Germany",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "EU grants/CORDIS search",
        "notes": "Pipedrive: Open (Data Entry stage) | Pre-screen: Pass",
    },
    {
        "name": "MaterialsZone",
        "description": "AI-powered materials informatics platform for battery and broader materials R&D.",
        "website": "materials.zone",
        "linkedin": "",
        "stage": "Series A",
        "geography": "Israel",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Crunchbase",
        "notes": "Pre-screen: Pass",
    },
    {
        "name": "Kebotix",
        "description": "Autonomous AI-driven materials discovery via a self-driving lab (robotics + ML); general materials discovery platform with plausible but unconfirmed battery-materials use cases.",
        "website": "kebotix.com",
        "linkedin": "",
        "stage": "Series B",
        "geography": "USA",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Accelerator alumni search",
        "notes": "Pipedrive: org-only, no deal record | Pre-screen: Pass | Mandate fit: battery-specific application unverified — general materials discovery platform, not battery-exclusive",
    },
    {
        "name": "PhaseTree",
        "description": "Cloud-based physics-AI platform for accelerating materials discovery, including battery materials; DTU (Denmark) spinout.",
        "website": "phasetree.ai",
        "linkedin": "",
        "stage": "Seed (~€3M, Mar 2025)",
        "geography": "Denmark",
        "segment": "General AI materials discovery platforms",
        "score": None,
        "source": "Open web",
        "notes": "Pipedrive: Open | Pre-screen: Pass",
    },
]

summary = (
    "Mode: COMPREHENSIVE (DEEP), regions EU+JP+US (geography=Global). "
    "This is a narrow, technically-specific niche: most battery-related deal flow found (via Herb memory, "
    "Pipedrive, and 45 scraped VC/CVC portfolios across JP/EU/US) is battery MANUFACTURING, recycling, or "
    "battery-management/analytics software (e.g. Nanograf, Group14, Sila, QuantumScape, ACCURE, Electroder, "
    "BattGenie, FION Energy) — excluded per the mandate's explicit scope (\"not battery manufacturing or "
    "battery management software\"). 18 companies made the longlist where AI/ML genuinely drives materials "
    "discovery/design; 4 failed pre-screen on stage only (Citrine Informatics: Series C; SES AI: publicly "
    "traded; Wildcat Discovery Technologies and Holyvolt: growth-stage/acquired) but are kept for visibility "
    "since they are directly on-thesis. No seed companies were provided; no named companies to force-include. "
    "icos_fit scoring was not requested (off by default) — all rows show score=None."
)

finish_run(ctx, companies, summary=summary)
print("DONE")
