RESOLVED = {
 "MycoTechnology": "mycoiq.com",
 "Culture Biosciences": "culturebiosciences.com",
 "Liberation Labs": "liberation.bio",
 "EnginZyme": "enginzyme.com",
 "The Protein Brewery": "theproteinbrewery.com",
 "StrainX Bioworks": "strainx.in",
 "Melazyme": "melazyme.com",
 "Triplebar Bio": "triplebar.com",
 "Capra Biosciences": "caprabiosciences.com",
 "c-LEcta GmbH": "c-lecta.com",
 "Recombia Biosciences": "recombia.com",
 "Cauldron": "cauldronferm.com",
 "Kuehnle AgroSystems": "kuehnleagro.com",
 "Esencia Foods": "esenciafoods.co",
 "NoPalm Oil": "nopalm-ingredients.com",
 "Differential Bio": "differential.bio",
 "Fermbox Bio": "fermbox.bio",
 "Zya": "zya.co",
 "Cosaic": "cosaic.bio",
 "LGEM": "lgem.com",
 "Flying Embers": "flyingembers.com",
 "Change Foods": "changefoods.com",
 "Algal Bio": "algalbio.co.jp",
 "Synonym Biotechnologies": "synonym.bio",
 "Enough (formerly 3F Bio)": "enough-food.com",
 "AuX Labs": "auxlabs.com",
}
