RESOLVED = {
    "C16 Biosciences": "c16bio.com",
    "Sennos": "sennos.com",
    "Sable Fermentation, Inc.": "sablefermentation.com",
    "Biosynth": "biosynth.com",
    "BioNukleo": "bionukleo.com",
    "All G": "allg.com",
    "Melt & Marble": "meltandmarble.com",
    "Enifer": "enifer.com",
    "Esencia Foods": "esenciafoods.co",
    "Clean Food Group": "cleanfood.group",
    "BIOCOLL": None,
    "Fermeate": None,
    "Plantible": None,
    "Capro-X": "capro-x.com",
    "Mothership Materials": "mothershipmaterials.com",
    "Rebus Biosystems": "rebusbio.com",
    "Unibio": "unibio.dk",
    "Imagindairy": "imagindairy.com",
    "String Bio": "stringbio.com",
    "MycoTechnology": "mycoiq.com",
    "Calysta": "calysta.com",
    "Culture Biosciences": "culturebiosciences.com",
    "Debut Biotech": "debutbiotech.com",
    "Sustainable Bioproducts": "naturesfynd.com",
    "Motif Ingredients": "madewithmotif.com",
    "Eden Brew": "edenbrew.com.au",
    "Cauldron Ferm": "cauldronferm.com",
    "Pacifico Biolabs": None,
    "Standing Ovation": "standing-ovation.co",
    "Liberation Bioindustries": "liberation.bio",
    "Chitose": "chitose-bio.com",
    "hydroGel": None,
    "Infinite Roots": "infiniteroots.com",
    "Abolis Biotechnologies": "abolis.fr",
    "The Protein Brewery": "theproteinbrewery.com",
    "Again": "again.bio",
    "Helaina": "myhelaina.com",
    "Pando Bioscience": "pando.bio",
    "Ligo Biosciences": "ligo.bio",
    "Differential Bio GmbH": "differential.bio",
    "Lygos": "lygos.com",
    "Bon Vivant": None,
    "FERMENTALG": "fermentalg.com",
    "Afyren": "afyren.com",
    "Arzeda": "arzeda.com",
}
RESOLVED.update({
    "Biosyntia": "biosyntia.com",
    "CelluComp": "cellucomp.com",
    "DNA Script": "dnascript.com",
    "Elicit Plant": "elicit-plant.com",
    "GFBiochemicals": "gfbiochemicals.com",
    "Meiogenix": "meiogenix.com",
    "MetGen": "metgen.com",
    "Micropep Technologies": "micro-pep.com",
    "Microphyt": "microphyt.eu",
    "P2 Science": "p2science.com",
    "Prometheus Materials": "prometheusmaterials.com",
    "Protera": "proterabio.com",
    "Qorium": "qorium.com",
    "Synthace": "synthace.com",
    "Verley": "verley-food.com",
    "Heura": "heurafoods.com",
    "VEGDOG": "vegdog.de",
    "NURITAS": "nuritas.com",
    "PROTIX": "protix.com",
    "eeden": None,
    "Genomines": "genomines.com",
    "SOLASTA Bio": "solastabio.com",
    "PACT": "pact.earth",
    "Planetary": "planetarygroup.ch",
    "Micro Harvest": "microharvest.com",
    "Switch Bioworks": "switchbioworks.com",
    "Reshape": "reshapebiotech.com",
    "Zya": "zya.co",
    "Amplifye": "amplifye.co",
    "Calyxia": "calyxia.com",
    "Modern Meadow": "modernmeadow.com",
    "Biofluff": None,
    "AmphiStar": "amphistar.com",
    "Rainbow Crops": "rainbowcrops.com",
    "Obulytix": "obulytix.com",
    "AIO": "aio.bio",
    "Aisti": None,
    "Avenue Biosciences": "avenuebiosciences.com",
    "Cellfion": None,
    "ArgusEye": "arguseyesensors.com",
    "Future Fields": "futurefields.io",
    "IntegriCulture": "integriculture.com",
    "Kula Bio": "kulabio.com",
    "Layrr": "layrr.co",
    "Bota Bio": "bota.bio",
})
RESOLVED.update({
    "Equinom": "equi-nom.com", "Provivi": "provivi.com", "BigRep GmbH": "bigrep.com", "Phomera": None, "Lactips": "lactips.com",
    "BiomEdit": "biomedit.com", "Aqua Theon": "aquatheon.com", "Algal Bio": "algalbio.co.jp", "Trillium": "trilliumchemicals.com", "Sirrus": None,
    "Elo Life": "elolife.com", "Enough": None, "Visolis": "visolisbio.com", "Asimov": "asimov.com", "Hyfe": "hyfe.tech",
    "Anthology": "anthology.bio",
    "Amide": "amidetech.com",
    "Kano": None,
    "Foray Bioscience": "foraybio.com",
    "Terragia": "terragia.com",
    "GreenLight Biosciences": "greenlightbiosciences.com",
    "New Culture": None,
    "ForeLight": "forelight.com",
    "Kuehnle AgroSystems": "kuehnleagro.com",
    "Mara Renewables": "maracorp.ca",
    "Avant": None,
    "Aspect Biosystems": "aspectbiosystems.com",
    "Correlia Biosystems": "correliabio.com",
    "Biodel AG": "biodelag.com",
    "Prime Roots": None,
    "NewLeaf Symbiotics": "newleafsym.com",
    "Membrion": "membrion.com",
    "Puna Bio": "puna.bio",
    "Hoofprint Biome": "hoofprintbiome.com",
    "iVexSol": "ivexsol.com",
    "Exactmer": "exactmer.com",
    "NFW Technologies": "nfw.earth",
    "Multus": "multus.bio",
})
