# Raw rows collected across all sources for run c086d3c8-f011-4aea-9ddd-3f29bef374d0
# Fields: name, domain, hq, fte, stage, raised, last_round, investors, tech, sectors, url, why_now, source

PIPEDRIVE = [
    dict(name="Pow.bio", domain="pow.bio", status="lost", pd_stage="Quickscan", reason="too early stage", updated="2026-07-10", desc="Developer of intelligent fermentation technology designed to solve the capacity problem. Combines continuous fermentation with advanced control methodology."),
    dict(name="Kidemis", domain="kidemis.com", status="open", pd_stage="Advanced Follow-up", reason="", updated="2026-06-17", desc="Producer of plant-based protein via mycelium-based fermentation converting industrial food waste into protein-content ingredients."),
    dict(name="Maya Milk", domain="mayamilk.com", status="open", pd_stage="Follow Up", reason="", updated="2026-01-08", desc="Producer of vegan dairy substitutes using precision fermentation to produce animal-origin-free dairy proteins and fats."),
    dict(name="Calidris Bio", domain="calidrisbio.com", status="open", pd_stage="Follow Up", reason="", updated="2026-03-22", desc="Manufacturer of microbe-based sustainable protein via natural fermentation process."),
    dict(name="Sestina Bio", domain="sestinabio.com", status="open", pd_stage="Leads", reason="", updated="2026-03-22", desc="Synthetic biology platform to engineer yeast and bacteria to produce chemicals and pharmaceuticals."),
    dict(name="MOA Foodtech", domain="moafoodtech.com", status="won", pd_stage="PUR/DD/FIP", reason="", updated="2026-03-22", desc="AI-driven fermentation platform (Albatros) upcycling food industry residues into high-value ingredients."),
    dict(name="3FBio", domain="3fbio.com", status="lost", pd_stage="Deals to Discuss", reason="too late stage", updated="2026-03-22", desc="Zero-waste fermentation of high-quality protein, converting starch to protein."),
    dict(name="Delft Advanced Biorenewables", domain="dab.bio", status="lost", pd_stage="Follow Up", reason="too early stage", updated="2026-03-22", desc="Bioreactor technology combining fermentation and separation of extracted components in one vessel."),
    dict(name="Arbiom", domain="arbiom.com", status="lost", pd_stage="Follow Up", reason="not competitive", updated="2026-03-22", desc="Bioprocessing/fermentation technology turning wood into protein for animal feed."),
    dict(name="Smobya", domain="smobya.com", status="lost", pd_stage="Deals to Discuss", reason="too early stage", updated="2026-03-22", desc="Cellulose manufacturing from food waste for plastic-free textile/leather materials via microbes."),
    dict(name="Sophie's Bionutrients", domain="sophiesbionutrients.com", status="lost", pd_stage="Deals to Discuss", reason="too early stage", updated="2026-03-22", desc="Grows microalgae in soybean residue via fermentation for alternative protein."),
    dict(name="NovoNutrients", domain="novonutrients.com", status="lost", pd_stage="Deals to Discuss", reason="too early stage", updated="2026-03-22", desc="Uses natural microbes to break down CO2/hydrogen into lowest-cost feed/food ingredients."),
    dict(name="protein fatco", domain="timetravellingmilkman.com", status="lost", pd_stage="Deals to Discuss", reason="disqualified in market scan", updated="2026-05-05", desc="Fat ingredients for dairy alternatives, extracted from seeds/plant materials."),
    dict(name="Enzymit", domain="enzymit.com", status="lost", pd_stage="Deals to Discuss", reason="too late stage", updated="2026-05-05", desc="Computational design platform augmented with deep-learning for enzyme/chemistry."),
    dict(name="Luya Foods", domain="luya.bio", status="lost", pd_stage="Deals to Discuss", reason="too early stage", updated="2026-05-05", desc="Combines traditional fermentation with modern technology to turn okara into food."),
    dict(name="BioTork", domain="biotork.com", status="lost", pd_stage="Deals to Discuss", reason="Not in focus region", updated="2026-05-05", desc="Biotechnology platform for bio-based chemical commodities via microbial strains/bioconversion."),
    dict(name="Hayden Biotech", domain="haydenbiotech.com", status="lost", pd_stage="Deals to Discuss", reason="Does not fit fund (ICF 4) strategy", updated="2025-07-08", desc="Biomanufacturing company making precision fermentation affordable/scalable via simplified bioreactors."),
    dict(name="FluIDect", domain="fluidect.com", status="lost", pd_stage="Data Entry", reason="Does not fit fund (ICF 4) strategy", updated="2026-07-01", desc="Microbial analytic instruments for seamless process monitoring/control using light-emitting microbeads."),
    dict(name="Arkeon Biotechnologies", domain="arkeon.bio", status="lost", pd_stage="Deals to Discuss", reason="Closed down", updated="2026-03-22", desc="Converts CO2 into protein ingredients using ancient microbes."),
    dict(name="Biotic (Bio-Circular)", domain="biotic-labs.com", status="lost", pd_stage="Deals to Discuss", reason="too early stage", updated="2026-03-22", desc="Fully bio-based biodegradable polymers from sea macro-algae."),
    dict(name="Locus Fermentation Solutions", domain="locusfs.com", status="lost", pd_stage="Leads", reason="too late stage", updated="2026-03-22", desc="Microbial/biosurfactant systems, patent-pending processes, modular low-capex facilities."),
    dict(name="Nutrition from Water", domain="nutritionfromwater.com", status="open", pd_stage="Quickscan", reason="", updated="2026-07-13", desc="Commercializes endemic microalgae strains via fermentation/biotechnology into sports nutrition."),
    dict(name="Nosh.bio", domain="nosh.bio", status="open", pd_stage="Advanced Follow-up", reason="", updated="2026-07-13", desc="Techno-functional ingredients via novel proprietary fermentation and mild downstream processing."),
    dict(name="ALGAEPRO", domain="greentechinnovators.no", status="open", pd_stage="Leads", reason="", updated="2026-05-11", desc="Automatic carbon-negative algae growth using food waste as fermentation input."),
    dict(name="SomaTech", domain="somatech.ie", status="open", pd_stage="Leads", reason="", updated="2026-03-22", desc="Solid-state fermentation platform to grow mushroom mycelium, upcycling plant side streams."),
    dict(name="N-fix", domain="zymofix.com", status="open", pd_stage="Corporate Follow-up", reason="", updated="2026-03-22", desc="Biofertilizers from recycled agricultural residues via solid state fermentation/hydrothermal carbonization."),
    dict(name="Chromologics", domain="chromologics.com", status="open", pd_stage="Corporate Follow-up", reason="", updated="2026-03-22", desc="Fermentation-derived natural colorant platform for bio-based food color pigments."),
    dict(name="SuperBrewed Food", domain="superbrewedfood.com", status="open", pd_stage="Corporate Follow-up", reason="", updated="2026-03-22", desc="Fermentation technology shifting carbon to ethanol production, boosting fermentation yields."),
    dict(name="AquaCultured Foods", domain="aquaculturedfoods.com", status="open", pd_stage="Leads", reason="", updated="2026-03-22", desc="Seafood alternative via microbial fermentation creating fibrous protein/probiotic threads."),
    dict(name="Fermtech", domain="fermtech.co.uk", status="won", pd_stage="Deals to Discuss", reason="", updated="2026-05-29", desc="Low-carbon protein via solid-state fermentation of brewery spent grains."),
    dict(name="Bar.on", domain="baron.bar", status="lost", pd_stage="Deals to Discuss", reason="no corporate buy-in", updated="2026-05-05", desc="Molecular mixing technology to recreate beer without fermentation."),
    dict(name="Rebio", domain="tmo-group.com", status="lost", pd_stage="Data Entry", reason="too late stage", updated="2023-12-27", desc="Converts thermophilic bacteria/fermentation of cellulosic sugars into bioethanol."),
    dict(name="Food and Feed Biotech S.L.", domain="mmmicoeats.com", status="lost", pd_stage="Data Entry", reason="No Reply", updated="2024-06-06", desc="Fermentation and directed evolution to create natural ingredients for food/nutraceuticals/cosmetics/feed."),
    dict(name="Bioboost Synbio", domain="bioboostsynbio.com", status="lost", pd_stage="Data Entry", reason="too early stage", updated="2024-06-20", desc="Sustainable yeast fermentation technology producing proteins/biomolecules."),
    dict(name="Porlammin Meijeri", domain="", status="lost", pd_stage="Data Entry", reason="Does not fit fund (ICF 4) strategy", updated="2024-07-05", desc="Finnish dairy company transforming food-tech via protein purification/cheese fermentation."),
    dict(name="SNL BioSolutions", domain="snlbiosolutions.com", status="lost", pd_stage="Data Entry", reason="too early stage", updated="2024-09-13", desc="Fermentation-based oils at scale from food ingredients to sustainable aviation fuel."),
    dict(name="VIFFFF", domain="vif4.com", status="lost", pd_stage="Data Entry", reason="Not interesting enough", updated="2025-07-17", desc="Vegan/gluten-free food combining Asian/European fermentation cycles."),
    dict(name="Evologic", domain="evologic-technologies.com", status="lost", pd_stage="Deals to Discuss", reason="Does not fit fund (ICF 4) strategy", updated="2026-05-05", desc="Bioprocessing company developing novel production methods for biostimulants."),
    dict(name="ZwitterCo", domain="zwitterco.com", status="open", pd_stage="Leads", reason="", updated="2026-03-22", desc="Reverse osmosis membrane technology for industrial water treatment/reuse."),
    dict(name="CellRX", domain="proteindirectory.com", status="lost", pd_stage="Data Entry", reason="Does not fit fund (ICF 4) strategy", updated="2026-01-13", desc="Manufacturer/supplier of growth factors serving technical research/bioprocessing markets."),
]

# Non-pipedrive rows from all web sources. Each tuple: (name, domain, hq, fte, stage, raised, last_round, investors, tech, sectors, why_now, source)
U = "Unknown"
WEB_ROWS = [
    # Seed expansion
    ("Rebus Biosystems", U, U, U, U, U, U, U, "Biomanufacturing", "Biotech", U, "seed-expansion"),
    ("Onego Bio", "onego.bio", "Finland", U, "Series A", U, U, U, "Precision fermentation for egg proteins", "Alternative protein, Biotech", "Egg protein production without poultry farming", "seed-expansion"),
    ("Perfect Day", U, U, U, U, U, U, U, "Precision fermentation for milk proteins", "Alternative protein, Dairy", "Commercial-scale precision fermentation viability", "seed-expansion"),
    ("Unibio", U, U, U, U, U, U, U, "Biotech fermentation", "Biotech", U, "seed-expansion"),
    ("Imagindairy", U, U, U, U, U, U, U, "Precision fermentation for dairy proteins", "Alternative protein, Dairy, Biotech", "Cost-effective animal-free dairy proteins", "seed-expansion"),
    ("Shiru", U, U, U, U, U, U, U, "AI-driven protein discovery and development", "Biotech, Alternative protein", "AI/bioinformatics-powered protein engineering", "seed-expansion"),
    ("String Bio", U, U, U, U, U, U, U, "Gas fermentation for sustainable ingredients", "Biotech, Alternative protein", "Advanced gas fermentation technology", "seed-expansion"),
    ("Formo", U, "Germany", U, "Series B", U, U, U, "Precision fermentation for milk proteins", "Biotech, Dairy, Alternative protein", "Milk protein ingredients replacing dairy", "seed-expansion"),
    ("MycoTechnology", U, U, U, U, U, U, U, "Fungal fermentation for food ingredients", "Biotech, Food ingredients", "Natural flavor enhancers via mushroom fermentation", "seed-expansion"),
    ("Calysta", U, U, U, U, U, U, U, "Fermentation and biomanufacturing", "Biotech, Alternative protein", U, "seed-expansion"),
    # Crunchbase
    ("Vivici", U, "Netherlands", U, "Series A", "EUR32.5M", "Feb 2025", U, "Precision fermentation, dairy proteins", "Food/Biotech", "Launching animal-free dairy proteins", "Crunchbase"),
    ("Culture Biosciences", U, U, U, U, U, U, U, "Bioreactor platform, fermentation-as-a-service", "Biotech", U, "Crunchbase"),
    ("Debut Biotech", U, U, U, U, U, U, U, "Microbial fermentation biotech", "Biotech", U, "Crunchbase"),
    ("Sustainable Bioproducts", U, U, U, "Series A", "$33M", U, U, U, "Biotech", U, "Crunchbase"),
    ("Motif Ingredients", U, U, U, "Series A", "$90M", U, U, U, "Biotech, Food", U, "Crunchbase"),
    ("Eden Brew", U, "Australia", U, "Series A", "$16M", U, U, "Precision fermentation dairy", "Food/Biotech", U, "Crunchbase"),
    # X/Twitter
    ("Cauldron Ferm", U, "Australia", U, "Series A2", "$13.25M", "2025", U, "Continuous hyper-fermentation", "Biotech, Fermentation", "Industrial biotech scaling with proprietary hyper-fermentation", "X/Twitter"),
    ("Pacifico Biolabs", U, "Germany", U, "Series A", "EUR7M", "2024-2025", "Stray Dog Capital, TGFS, Sprout & About Ventures, Simon Capital, FoodLabs", "Mycelium fermentation protein", "Biotech, Sustainable Protein", "Repurposing brewery infrastructure for protein production", "X/Twitter"),
    ("Standing Ovation", U, "France", U, "Series B", "$34.2M", "2026", "Bpifrance Ecotechnologies 2, Credit Mutuel Innovation", "Precision fermentation", "Biotech, Food", "Government-backed scaling for alternative proteins", "X/Twitter"),
    ("Liberation Bioindustries", U, "United States", U, "Series A", "$60M", "2025", U, "Fermentation biomanufacturing", "Biotech, Industrial Biotech", "Building fermentation facilities in US and Saudi Arabia", "X/Twitter"),
    # LinkedIn
    ("C16 Biosciences", U, "USA", U, "Series A", "$20M", "2020", "Breakthrough Energy Ventures, Waldencast, Y Combinator, DCVC, Sound Ventures, AME Cloud Ventures", "Precision fermentation", "Sustainable fats/oils, consumer products", "Scaling bio-based palm oil alternative", "LinkedIn"),
    ("Sennos", U, "USA", U, U, U, U, U, "Precision fermentation, AI sensing", "Industrial biotech monitoring", "Real-time fermentation analytics platform", "LinkedIn"),
    ("Sable Fermentation, Inc.", U, "USA", U, U, U, U, U, "Continuous fermentation tech", "Industrial biotech", "Continuous fermentation platform", "LinkedIn"),
    ("Biosynth", U, "Europe", U, U, U, U, U, "Bioprocessing", "Biotech services", U, "LinkedIn"),
    ("BioNukleo", U, "Germany", U, U, U, U, U, "Bioprocessing engineering", "Industrial biotech", "TU Berlin spin-off", "LinkedIn"),
    ("All G", U, "Australia", U, U, U, U, U, "Precision fermentation", "Milk proteins", "Developing high-value proteins", "LinkedIn"),
    # Conferences EU
    ("Melt & Marble", U, "Sweden", U, "Series A", "EUR7.3M/2.5M", "2024", "Industrifonden", "Precision fermentation, designer fats", "Food/Biotech, Cosmetics", "EIC Accelerator March 2024 / scaling for 2026 launches", "Conferences EU"),
    ("Enifer", U, "Finland", U, "Series B", "EUR36-60M", "2024", U, "Mycoprotein (PEKILO), fungal fermentation", "Food/Biotech", "VTT spin-off; opening first commercial mycoprotein plant 2025", "Conferences EU"),
    ("Esencia Foods", U, "Germany", U, "Pre-Series", "EUR50K", "2024", U, "Mycelium seafood analogues", "Food/Biotech", "EIT Food 2024 winner", "Conferences EU"),
    ("Clean Food Group", U, "UK", U, "Pre-Series", "EUR30K", "2024", U, "Waste bread fermentation, palm oil alternative", "Food/Biotech", "EIT Food 2024 winner", "Conferences EU"),
    ("BIOCOLL", U, U, U, U, U, U, U, "Animal-free collagen, fungal fermentation", "Food/Biotech", "Slush 2025 participant", "Conferences EU"),
    # Conferences JP
    ("Spiber", "spiber.inc", "Japan", U, "Late-stage", "$489M total / $65M latest", "April 2024", "Carlyle", "Microbial-fermentation synthetic biology, Brewed Protein", "Biomaterials, textiles", "Climate-friendly alternatives; Japan positioning as fermentation biotech hub", "Conferences JP"),
    # Conferences US
    ("Fermeate", U, "US (California)", U, "Seed", "$2M", "2026", U, "Optogenetic fermentation control", "Industrial Biotech", "Step-change in precision fermentation economics", "Conferences US"),
    ("Plantible", U, U, U, U, U, U, U, "Plant-based protein fermentation", "Food/Nutrition", "IFT FIRST 2025 Grand Prize winner", "Conferences US"),
    ("Capro-X", U, "US", U, "Seed", U, U, U, U, "Industrial Biotech", "IndieBio NY 2025", "Conferences US"),
    ("Mothership Materials", U, "US", U, "Seed", U, U, U, U, "Advanced Materials", "IndieBio NY 2025", "Conferences US"),
    # Tech-transfer JP
    ("Chitose", U, "Japan", U, U, U, U, U, "Continuous fermentation (biopharma, bio jet-fuel, algae)", "Biotech, fermentation, biofuels", "Japan-based fermentation heritage play", "Tech-transfer JP"),
    # Tech-transfer US
    ("Berkeley Yeast", "berkeleyyeast.com", "US", U, "Series A", "$12.1M", "May 2023", "Anterra Capital, USDA, HHS, NSF, Collab+Currency", "Bioengineered yeast strains for fermentation", "Fermentation, Biotech, Alternative Proteins", "UC Berkeley spinout; enables continuous fermentation optimization", "Tech-transfer US"),
    ("hydroGel", U, "US", U, "Seed", U, U, U, "Polymeric resins for fermentation product purification", "Fermentation, Biotech", "MIT spinout; purification platform", "Tech-transfer US"),
    # Press EU
    ("Infinite Roots", U, "Germany", U, "Series B", "$58M", "Jan 2024", "EIC-backed", "Mycelium-based protein", "Alternative protein", "Mycelium scaling as alternative protein solution", "Press EU"),
    ("Abolis Biotechnologies", U, "France", U, U, "EUR35M", "Sep 2024", U, "Microbial ecosystem engineering for biomanufacturing", "Biotech, biomanufacturing", "Scaling microbial manufacturing platforms", "Press EU"),
    ("The Protein Brewery", U, "Netherlands", U, "Series B", "EUR30M", U, "Invest-NL, Novo Holdings", "Precision fermentation proteins", "Alternative protein", "Scaling fermentation-based protein production", "Press EU"),
    ("Again", U, U, U, "Series A", "$43M", U, U, "CO2 conversion to carbon-negative chemicals via biomanufacturing", "Climate tech, biomanufacturing", "Scaling CO2-to-chemicals transformation", "Press EU"),
    # Press JP
    ("Fermelanta", "fermelanta.com", "Japan", U, "Series A", "JPY4.8B/2B", "Sep 2025", "SMBC Venture Capital, Angel Bridge, Keio Innovation Initiative, Norinchukin Capital, Beyond Next Ventures, Hokuriku Startup Community Fund, Mitsubishi UFJ Capital, Miyako Capital, Universal Materials Incubator", "Synthetic biology; microbial fermentation", "Plant compounds; agrochemicals; bioactive ingredients", "Pilot plant 2026; Deep Tech government support", "Press JP"),
    # Press US
    ("Helaina", U, "US", U, "Series A", "$20M", U, U, "Precision fermentation (milk proteins)", "Infant formula", U, "Press US"),
    ("Cleveland Kitchen", U, "US", U, "Series A", "$19M", U, U, "Fermented foods", "Food", U, "Press US"),
    ("Joywell", U, "US", U, "Series B", "$25M", U, U, "Microbial fermentation", "Beverages", U, "Press US"),
    # Accelerator alumni
    ("Pando Bioscience", U, "US", U, U, U, U, U, "AI-driven enzyme engineering with high-throughput screening", "Biomanufacturing", "Accelerates enzyme optimization for fermentation-dependent biopharma", "Accelerator alumni"),
    ("Ligo Biosciences", U, "US", U, U, U, U, U, "Deep-learning enzyme design for cost reduction", "Industrial biotech, enzyme engineering", "AI-powered enzyme engineering for fermentation optimization", "Accelerator alumni"),
    ("Differential Bio GmbH", U, "Germany", U, U, U, U, U, "Robotic lab automation + AI for microbial growth", "Fermentation R&D", "Scalable fermentation process development via automation", "Accelerator alumni"),
    ("Lygos", U, "US", U, U, U, U, U, "Microbial engineering for fermentation", "Industrial chemicals", "Biological fermentation production of chemicals from sugars", "Accelerator alumni"),
    # Non-English EU
    ("Bon Vivant", U, "France", U, "Series A", "EUR15M", "2024-25", "Sofinnova Partners, Sparkfood, Captech Sante", "Precision fermentation", "Alternative dairy proteins", "Alt protein market growth", "Non-English EU"),
    ("FERMENTALG", U, "France", U, "Series B", "EUR12M", "2024-25", U, "Industrial fermentation", "Biotech/production", "Production scale-up phase", "Non-English EU"),
    # VC portfolio group 1
    ("Afyren", U, U, U, U, U, U, "Sofinnova Partners", "Bio-based chemicals", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Arzeda", U, U, U, U, U, U, "Sofinnova Partners", "Protein engineering", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Avantium", U, U, U, U, U, U, "Sofinnova Partners", "Advanced materials, specialty chemicals", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Biosyntia", U, U, U, U, U, U, "Sofinnova Partners, ECBF", "Synthetic biology", "Industrial Biotech", U, "VC-portfolio (Sofinnova/ECBF)"),
    ("Biotalys", U, U, U, U, U, U, "Sofinnova Partners", "Biotech solutions", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("CelluComp", U, U, U, U, U, U, "Sofinnova Partners", "Materials science", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("DNA Script", U, U, U, U, U, U, "Sofinnova Partners, M Ventures", "Biotechnology manufacturing (DNA synthesis)", "Industrial Biotech", U, "VC-portfolio (Sofinnova/M Ventures)"),
    ("Elicit Plant", U, U, U, U, U, U, "Sofinnova Partners", "Plant-based bioprocessing", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("EnginZyme", "enginzyme.com", "Sweden", U, U, U, U, "Sofinnova Partners, Industrifonden", "Cell-free biomanufacturing", "Industrial Biotech", U, "VC-portfolio (Sofinnova/Industrifonden)"),
    ("GFBiochemicals", U, U, U, U, U, U, "Sofinnova Partners", "Biochemical production", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Meiogenix", U, U, U, U, U, U, "Sofinnova Partners", "Biotech innovation", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("MetGen", U, U, U, U, U, U, "Sofinnova Partners", "Metabolic engineering (enzymes)", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Micropep Technologies", U, U, U, U, U, U, "Sofinnova Partners", "Peptide production", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Microphyt", U, U, U, U, U, U, "Sofinnova Partners", "Microalgae solutions", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Novameat", U, U, U, U, U, U, "Sofinnova Partners, Astanor, Forbion", "Alternative protein (3D printing)", "Food/Nutrition", U, "VC-portfolio (Sofinnova/Astanor/Forbion)"),
    ("P2 Science", U, U, U, U, U, U, "Sofinnova Partners, BASF Venture Capital", "Chemical synthesis", "Industrial Biotech", U, "VC-portfolio (Sofinnova/BASF VC)"),
    ("Prometheus Materials", U, U, U, U, U, U, "Sofinnova Partners", "Advanced materials (biomineralized cement)", "Advanced Materials", U, "VC-portfolio (Sofinnova)"),
    ("Protera", U, U, U, U, U, U, "Sofinnova Partners", "Protein engineering (AI)", "Industrial Biotech", U, "VC-portfolio (Sofinnova)"),
    ("Qorium", U, U, U, U, U, U, "Sofinnova Partners", "Biotech platform (cultivated leather)", "Advanced Materials", U, "VC-portfolio (Sofinnova)"),
    ("Synthace", U, U, U, U, U, U, "Sofinnova Partners", "Bioprocessing automation software", "Bioprocessing", U, "VC-portfolio (Sofinnova)"),
    ("Verley", U, U, U, U, U, U, "Sofinnova Partners", "Food/nutrition innovation", "Food/Nutrition", U, "VC-portfolio (Sofinnova)"),
    ("Heura", U, U, U, U, U, U, "ECBF", "Plant-based food", "Food/Nutrition", U, "VC-portfolio (ECBF)"),
    ("VEGDOG", U, U, U, U, U, U, "ECBF", "Sustainable pet nutrition", "Food/Nutrition", U, "VC-portfolio (ECBF)"),
    ("NURITAS", U, U, U, U, U, U, "ECBF", "Food/Nutrition biotech (AI peptide discovery)", "Food/Nutrition", U, "VC-portfolio (ECBF)"),
    ("PROTIX", U, U, U, U, U, U, "ECBF", "Insect protein alternative", "Food/Nutrition", U, "VC-portfolio (ECBF)"),
    ("eeden", U, U, U, U, U, U, "Forbion", "Textile recycling (biotech)", "Advanced Materials", U, "VC-portfolio (Forbion)"),
    ("Genomines", U, U, U, U, U, U, "Forbion", "Plant biotechnology (phytomining)", "Industrial Biotech", U, "VC-portfolio (Forbion)"),
    ("SOLASTA Bio", U, U, U, U, U, U, "Forbion", "Synthetic biology (biopesticides)", "Industrial Biotech", U, "VC-portfolio (Forbion)"),
    ("PACT", U, U, U, U, U, U, "Forbion", "Biomaterial platform", "Advanced Materials", U, "VC-portfolio (Forbion)"),
    ("Octarine Bio", "octarinebio.com", U, U, U, U, U, "DSM-Firmenich", "Synthetic biology (cannabinoids)", "Industrial Biotech", U, "VC-portfolio (DSM-Firmenich)"),
    ("Phynova", "phynova.com", U, U, U, U, U, "DSM-Firmenich", "Specialty chemicals (plant extracts)", "Industrial Biotech", U, "VC-portfolio (DSM-Firmenich)"),
    ("Isobionics", "isobionics.com", U, U, U, U, U, "DSM-Firmenich", "Fermentation (flavor/fragrance ingredients)", "Bioprocessing", U, "VC-portfolio (DSM-Firmenich)"),
    ("Phytolon", "phytolon.com", U, U, U, U, U, "DSM-Firmenich", "Sustainable ingredients (natural colors)", "Food/Nutrition", U, "VC-portfolio (DSM-Firmenich)"),
    ("Incredosugar", "incredosugar.com", U, U, U, U, U, "DSM-Firmenich", "Food ingredients (sugar reduction)", "Food/Nutrition", U, "VC-portfolio (DSM-Firmenich)"),
    ("Chinova Bioworks", "chinovabioworks.com", U, U, U, U, U, "DSM-Firmenich", "Food technology (mushroom-based preservative)", "Food/Nutrition", U, "VC-portfolio (DSM-Firmenich)"),
    ("Planetary", U, U, U, "Venture", U, U, "Astanor", "Bioreactor infrastructure (ocean alkalinity)", "Bioprocessing", U, "VC-portfolio (Astanor)"),
    ("Micro Harvest", U, U, U, "Venture", U, U, "Astanor", "Fermentation (single cell protein)", "Food/Nutrition", U, "VC-portfolio (Astanor)"),
    ("Switch Bioworks", U, U, U, "Seed", U, U, "Astanor", "Synthetic biology (gas fermentation)", "Industrial Biotech", U, "VC-portfolio (Astanor)"),
    ("Reshape", U, U, U, "Venture", U, U, "Astanor", "Robotics", "Industrial Biotech", U, "VC-portfolio (Astanor)"),
    ("Zya", U, U, U, "Venture", U, U, "Astanor", "Enzyme technology", "Food/Nutrition", U, "VC-portfolio (Astanor)"),
    ("Amplifye", U, U, U, "Venture", U, U, "Astanor", "Protein optimization", "Food/Nutrition", U, "VC-portfolio (Astanor)"),
    ("v2Food", U, U, U, "Venture", U, U, "Astanor", "Plant-based meat", "Food/Nutrition", U, "VC-portfolio (Astanor)"),
    ("Swap", U, U, U, "Venture", U, U, "Astanor", "Plant-based protein", "Food/Nutrition", U, "VC-portfolio (Astanor)"),
    ("Calyxia", U, U, U, "Venture", U, U, "Astanor", "Green chemistry (microencapsulation)", "Advanced Materials", U, "VC-portfolio (Astanor)"),
    ("Modern Meadow", U, U, U, "Venture", U, U, "Astanor", "Biofabrication (biomaterials)", "Advanced Materials", U, "VC-portfolio (Astanor)"),
    ("Biofluff", U, U, U, "Seed", U, U, "Astanor", "Textile materials (mycelium fiber)", "Advanced Materials", U, "VC-portfolio (Astanor)"),
    ("AmphiStar", U, U, U, U, U, U, "Qbic Fund", "Biosurfactants", "Bioprocessing", U, "VC-portfolio (Qbic)"),
    ("Rainbow Crops", U, U, U, U, U, U, "Qbic Fund", "Synthetic biology (crop traits)", "Industrial Biotech", U, "VC-portfolio (Qbic)"),
    ("Obulytix", U, U, U, U, U, U, "Qbic Fund", "Enzyme technology", "Industrial Biotech", U, "VC-portfolio (Qbic)"),
    ("Cellevate", "cellevate.com", "Sweden", U, U, U, U, "Industrifonden", "Nanofiber bioprocessing", "Bioprocessing", U, "VC-portfolio (Industrifonden)"),
    ("Agteria", "agteria.com", "Sweden", U, U, U, U, "Industrifonden", "Fermentation (feed additive for methane reduction)", "Industrial Biotech", U, "VC-portfolio (Industrifonden)"),
    ("Arevo", "arevo.se", "Sweden", U, U, U, U, "Industrifonden", "Plant nutrition (biostimulants)", "Food/Nutrition", U, "VC-portfolio (Industrifonden)"),
    ("AIO", U, U, U, U, U, U, "Voima Ventures, Nordic Foodtech VC", "Microbial oils (fermentation)", "Food/Nutrition", U, "VC-portfolio (Voima/Nordic Foodtech)"),
    ("Aisti", U, U, U, U, U, U, "Voima Ventures", "Acoustic materials", "Advanced Materials", U, "VC-portfolio (Voima)"),
    ("Avenue Biosciences", U, U, U, U, U, U, "Voima Ventures", "Synthetic biology", "Industrial Biotech", U, "VC-portfolio (Voima)"),
    ("Cellfion", U, U, U, U, U, U, "Voima Ventures", "Bio-based membranes", "Advanced Materials", U, "VC-portfolio (Voima)"),
    ("ArgusEye", U, U, U, U, U, U, "Voima Ventures", "Bioprocessing monitoring (sensors)", "Bioprocessing", U, "VC-portfolio (Voima)"),
    ("Evodia", "evodiabio.com", U, U, U, U, U, "Nordic Foodtech VC", "Fermentation", "Food/Nutrition", U, "VC-portfolio (Nordic Foodtech VC)"),
    ("Ironic Biotech", "ironicbiotech.com", U, U, U, U, U, "Nordic Foodtech VC", "Fermentation", "Food/Nutrition", U, "VC-portfolio (Nordic Foodtech VC)"),
    ("Future Fields", U, U, U, U, "$8M", "Jun 2025", "AgFunder, Amplify Capital, R7 Partners", "Bioprocessing (recombinant protein production)", "Bioprocessing", U, "VC-portfolio (AgFunder) / Press US"),
    ("IntegriCulture", U, "Japan", U, U, U, U, "AgFunder, Untrod, Beyond Next Ventures", "Bioprocessing (cultivated meat)", "Bioprocessing, Food", U, "VC-portfolio (AgFunder/Untrod/Beyond Next)"),
    ("Brightseed", U, U, U, U, U, U, "AgFunder", "Food/Nutrition biotech (AI bioactives discovery)", "Food/Nutrition", U, "VC-portfolio (AgFunder)"),
    ("Kula Bio", U, U, U, U, U, U, "AgFunder", "Industrial biotech (biofertilizer)", "Industrial Biotech", U, "VC-portfolio (AgFunder)"),
    ("Layrr", U, U, U, U, U, U, "AgFunder", "Advanced materials", "Advanced Materials", U, "VC-portfolio (AgFunder)"),
    ("Bota Bio", U, U, U, U, U, U, "BASF Venture Capital", "Industrial biology (synbio manufacturing)", "Industrial Biotech", U, "VC-portfolio (BASF VC)"),
    ("Equinom", U, U, U, U, U, U, "BASF Venture Capital", "Agricultural biotech (seed breeding)", "Industrial Biotech", U, "VC-portfolio (BASF VC)"),
    ("Provivi", U, U, U, U, U, U, "BASF Venture Capital", "Specialty chemicals (biopesticides)", "Industrial Biotech", U, "VC-portfolio (BASF VC)"),
    ("BigRep GmbH", U, "Germany", U, U, U, U, "BASF Venture Capital", "Advanced materials (3D printing)", "Advanced Materials", U, "VC-portfolio (BASF VC)"),
    ("Phomera", U, U, U, U, U, U, "BASF Venture Capital", "Advanced materials", "Advanced Materials", U, "VC-portfolio (BASF VC)"),
    ("Lactips", U, "France", U, U, U, U, "BASF Venture Capital", "Bio-based materials (water-soluble plastic)", "Advanced Materials", U, "VC-portfolio (BASF VC)"),
    ("Impossible Foods", "impossiblefoods.com", "US", U, "Growth", U, U, "Khosla Ventures", "Plant-based food", "Food/Nutrition", U, "VC-portfolio (Khosla)"),
    ("Leaft", "leaftfoods.com", U, U, "Growth", U, U, "Khosla Ventures", "Food/Nutrition biotech (leaf protein)", "Food/Nutrition", U, "VC-portfolio (Khosla)"),
    ("Pearl Bio", "pearlbio.com", U, U, "Growth", U, U, "Khosla Ventures", "Biomaterials (cell-free protein production)", "Advanced Materials", U, "VC-portfolio (Khosla)"),
    ("Enko", U, U, U, U, U, U, "Anterra Capital", "Crop protection (AI discovery)", "Industrial Biotech", U, "VC-portfolio (Anterra)"),
    ("BiomEdit", U, U, U, U, U, U, "Anterra Capital", "Animal health biotech (microbiome)", "Industrial Biotech", U, "VC-portfolio (Anterra)"),
    # VC portfolio group 2 (JP-heavy)
    ("Industrial Microbes Inc.", "imicrobes.com", U, U, U, U, U, "Universal Materials Incubator (UMI)", "Fermentation-based production", "Industrial Biotech", U, "VC-portfolio (UMI)"),
    ("Green Culture Inc.", "greenculture.co.jp", "Japan", U, U, U, U, "Universal Materials Incubator (UMI)", "Cultivation technology", "Biotech, Food", U, "VC-portfolio (UMI)"),
    ("bitBiome Inc.", "bitbiome.co.jp", "Japan", U, U, U, U, "UMI, UTEC", "Microbial genomics for biomanufacturing", "Biotech, Industrial Biotech", U, "VC-portfolio (UMI/UTEC)"),
    ("CellFiber Co., Ltd.", "cellfiber.jp", "Japan", U, U, U, U, "UMI, Untrod", "Cell-based fiber production, mass cell culture", "Advanced Materials, Bioprocessing", U, "VC-portfolio (UMI/Untrod)"),
    ("JEPLAN Inc.", "jeplan.co.jp", "Japan", U, U, U, U, "UMI", "Material recycling and chemical processing", "Specialty Chemicals", U, "VC-portfolio (UMI)"),
    ("EF Polymer K.K.", "efpolymer.com", U, U, U, U, U, "UMI, Beyond Next Ventures", "Biodegradable polymers", "Advanced Materials", U, "VC-portfolio (UMI/Beyond Next)"),
    ("Polyuse Inc.", "polyuse.xyz", "Japan", U, U, U, U, "UMI", "Sustainable polymers (construction)", "Advanced Materials", U, "VC-portfolio (UMI)"),
    ("Umami Bioworks", "umamibioworks.com", "Singapore", U, U, U, U, "Untrod", "Cell-based seafood production", "Synthetic Biology, Food", U, "VC-portfolio (Untrod)"),
    ("Bali Grove", "eatkarana.com", "Singapore", U, U, U, U, "Untrod", "Plant-based jackfruit meat", "Food, Plant-based", U, "VC-portfolio (Untrod)"),
    ("JALA Tech", "jala.tech", "Singapore", U, U, U, U, "Untrod", "Aquaculture/shrimp marketplace tech", "AgBiotech", U, "VC-portfolio (Untrod)"),
    ("Austrianova", "austrianova.com", "Singapore", U, U, U, U, "Untrod", "Cell and bacteria encapsulation technology", "Bioprocessing", U, "VC-portfolio (Untrod)"),
    ("ceEntek", "ceentek.com", "Singapore", U, U, U, U, "Untrod", "Carbon nano fiber paste", "Advanced Materials", U, "VC-portfolio (Untrod)"),
    ("SEPPURE", "seppure.com", "Singapore", U, U, U, U, "Untrod", "Nanofiltration membranes", "Advanced Materials", U, "VC-portfolio (Untrod)"),
    ("Accelerated Materials", "acceleratedmaterials.co", "Singapore", U, U, U, U, "Untrod", "Nanomaterial synthesis platform", "Advanced Materials", U, "VC-portfolio (Untrod)"),
    ("Epsilon Molecular Engineering", "epsilon-mol.co.jp", "Japan", U, U, U, U, "Untrod", "Antibody molecule design", "Synthetic Biology", U, "VC-portfolio (Untrod)"),
    ("GRA&GREEN", "gragreen.com", "Japan", U, U, U, U, "Beyond Next Ventures", "Genome editing for crop development", "AgBiotech", U, "VC-portfolio (Beyond Next)"),
    ("Symbiobe", "symbiobe.jp", "Japan", U, U, U, U, "Beyond Next Ventures", "Biomass and photosynthetic organisms", "Biotech, Circular Economy", U, "VC-portfolio (Beyond Next)"),
    ("AlgaleX", "algalex.com", "India", U, U, U, U, "Beyond Next Ventures", "Algae-based components from food waste", "Biotech", U, "VC-portfolio (Beyond Next)"),
    ("UMAMI UNITED", "umamiunited.com", "Japan", U, U, U, U, "Beyond Next Ventures", "Plant-based egg R&D", "Food, Synthetic Biology", U, "VC-portfolio (Beyond Next)"),
    ("Rhinoflux", "rhinoflux.com", "Japan", U, U, U, U, "Beyond Next Ventures", "Bioenergy carbon capture plants", "Advanced Materials, Energy", U, "VC-portfolio (Beyond Next)"),
    ("The Ethical Spirits & Co.", "ethicalspirits.jp", "Japan", U, U, U, U, "Beyond Next Ventures", "Regenerative distillery (fermentation upcycling)", "Specialty Chemicals, Food", U, "VC-portfolio (Beyond Next)"),
    ("Aqua Theon", U, "Japan", U, U, U, U, "Beyond Next Ventures", "Seaweed technology applications", "Food, Biotech", U, "VC-portfolio (Beyond Next)"),
    ("Algal Bio", U, "Japan", U, U, U, U, "UTEC", "Algae-based functional ingredients", "Biotech, Food", U, "VC-portfolio (UTEC)"),
    ("Trillium", U, U, U, U, U, U, "Capricorn Partners", "Bio-based acrylonitrile production", "Specialty Chemicals, Advanced Materials", U, "VC-portfolio (Capricorn)"),
    ("Sirrus", U, U, U, U, U, U, "Mitsui & Co. Global Investment", "Methylene malonates chemistry", "Specialty Chemicals", U, "VC-portfolio (Mitsui MGI)"),
    # VC portfolio group 3 (US-heavy)
    ("Elo Life", U, U, U, U, U, U, "DCVC", "Molecular farming for food ingredients", "Synthetic Biology, Food/Nutrition", U, "VC-portfolio (DCVC)"),
    ("Enough", U, U, U, U, U, U, "DCVC", "Fungal protein via fermentation", "Fermentation, Food/Nutrition", U, "VC-portfolio (DCVC)"),
    ("Ginkgo Bioworks", U, U, U, U, U, U, "DCVC", "Programming cells for production", "Synthetic Biology, Advanced Materials", U, "VC-portfolio (DCVC)"),
    ("MycoWorks", U, U, U, U, U, U, "DCVC", "Mycelium-based leather alternative", "Advanced Materials, Fermentation", U, "VC-portfolio (DCVC)"),
    ("Visolis", U, U, U, U, U, U, "DCVC", "Synthetic biology for carbon-negative materials", "Synthetic Biology, Advanced Materials", U, "VC-portfolio (DCVC)"),
    ("Asimov", U, U, U, U, U, U, "DCVC", "Genetic engineering platform (cell programming)", "Synthetic Biology", U, "VC-portfolio (DCVC)"),
    ("Hyfe", U, U, U, U, U, U, "The Engine Ventures", "Wastewater feedstock for biomanufacturing", "Bioprocessing, Industrial Biotech", U, "VC-portfolio (The Engine)"),
    ("Anthology", U, U, U, U, U, U, "The Engine Ventures", "Genome generation for biomanufacturing", "Bioprocessing, Synthetic Biology", U, "VC-portfolio (The Engine)"),
    ("Amide", U, U, U, U, U, U, "The Engine Ventures", "Robotic peptide and protein synthesis", "Industrial Biotech, Synthetic Biology", U, "VC-portfolio (The Engine)"),
    ("Kano", U, U, U, U, U, U, "The Engine Ventures", "Precision genomic editing", "Synthetic Biology", U, "VC-portfolio (The Engine)"),
    ("Foray Bioscience", U, U, U, U, U, U, "The Engine Ventures", "Plant cell biotech for ecosystem restoration", "Synthetic Biology, Industrial Biotech", U, "VC-portfolio (The Engine)"),
    ("Terragia", U, U, U, U, U, U, "The Engine Ventures", "Sustainable biofuels with biology", "Industrial Biotech", U, "VC-portfolio (The Engine)"),
    ("Tierra Biosciences", "tierrabiosciences.com", U, U, U, U, U, "Material Impact", "Synthetic biology protein manufacturing (cell-free)", "Synthetic Biology, Bioprocessing", U, "VC-portfolio (Material Impact)"),
    ("6K Inc", "6kinc.com", U, U, U, U, U, "Material Impact", "Advanced materials via microwave plasma", "Advanced Materials", U, "VC-portfolio (Material Impact)"),
    ("Mattiq", "mattiq.com", U, U, U, U, U, "Material Impact", "Nanomaterials libraries (AI-driven)", "Advanced Materials", U, "VC-portfolio (Material Impact)"),
    ("Huue", "huue.bio", U, U, U, U, U, "Material Impact", "Biosynthetic dyes (fermentation-derived indigo)", "Specialty Chemicals, Synthetic Biology", U, "VC-portfolio (Material Impact)"),
    ("Werewool", "werewool.bio", U, U, U, U, U, "Material Impact", "Protein-based textile fibers", "Advanced Materials, Synthetic Biology", U, "VC-portfolio (Material Impact)"),
    ("Ripple Foods", "ripplefoods.com", U, U, U, U, U, "Material Impact", "Dairy alternative from pea protein", "Food/Nutrition", U, "VC-portfolio (Material Impact)"),
    ("Talus Renewables", "talusag.com", U, U, U, U, U, "Material Impact", "Green ammonia production (modular)", "Specialty Chemicals", U, "VC-portfolio (Material Impact)"),
    ("GreenLight Biosciences", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Bio-production platform for RNA solutions", "Bioprocessing, Synthetic Biology", U, "VC-portfolio (S2G)"),
    ("New Culture", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Precision fermentation dairy alternative", "Fermentation, Food/Nutrition", U, "VC-portfolio (S2G)"),
    ("ForeLight", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Natural ingredients via photosynthetic organisms", "Bioprocessing, Food/Nutrition", U, "VC-portfolio (S2G)"),
    ("Kuehnle AgroSystems", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Microalgal ingredients via fermentation", "Fermentation, Food/Nutrition", U, "VC-portfolio (S2G)"),
    ("Mara Renewables", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Algae-derived Omega-3s", "Bioprocessing, Food/Nutrition", U, "VC-portfolio (S2G)"),
    ("Avant", U, U, U, "Venture, Growth", U, U, "S2G Investments", "Cell-cultivated marine proteins", "Bioprocessing, Food/Nutrition", U, "VC-portfolio (S2G)"),
    ("Aspect Biosystems", U, U, U, U, U, U, "Pangaea Ventures", "Bioprocessing systems (3D bioprinting)", "Bioprocessing, Synthetic Biology", U, "VC-portfolio (Pangaea)"),
    ("Correlia Biosystems", U, U, U, U, U, U, "Pangaea Ventures", "Synthetic biology platform", "Synthetic Biology", U, "VC-portfolio (Pangaea)"),
    ("Biodel AG", U, U, U, U, U, U, "Pangaea Ventures", "Industrial biotech", "Industrial Biotech, Food/Nutrition", U, "VC-portfolio (Pangaea)"),
    ("Prime Roots", U, U, U, U, U, U, "Pangaea Ventures", "Mycoprotein via fermentation", "Fermentation, Food/Nutrition", U, "VC-portfolio (Pangaea)"),
    ("NewLeaf Symbiotics", U, U, U, U, U, U, "Pangaea Ventures", "Industrial biotech for specialty chemicals (biologicals)", "Industrial Biotech, Specialty Chemicals", U, "VC-portfolio (Pangaea)"),
    ("Membrion", U, U, U, U, U, U, "Pangaea Ventures", "Specialty chemicals and bioprocessing (ceramic membranes)", "Specialty Chemicals, Bioprocessing", U, "VC-portfolio (Pangaea)"),
    ("Boston Bioprocess", "bostonbioprocess.com", U, U, U, U, U, "Clear Current Capital", "Bioprocessing (fermentation process development services)", "Bioprocessing", U, "VC-portfolio (Clear Current Capital)"),
    ("Concert Bio", "concert.bio", U, U, U, U, U, "Clear Current Capital", "Synthetic biology", "Synthetic Biology", U, "VC-portfolio (Clear Current Capital)"),
    ("Sunflower", "sunflowertx.com", U, U, U, U, U, "Clear Current Capital", "Advanced materials", "Advanced Materials", U, "VC-portfolio (Clear Current Capital)"),
    ("Brightly", "brightly.earth", U, U, U, U, U, "Clear Current Capital", "Specialty chemicals", "Specialty Chemicals", U, "VC-portfolio (Clear Current Capital)"),
    ("Blue Nalu", "bluenalu.com", U, U, U, U, U, "Clear Current Capital", "Cell cultivation for seafood", "Bioprocessing, Food/Nutrition", U, "VC-portfolio (Clear Current Capital)"),
    ("Puna Bio", U, "Argentina/US", U, "Seed", U, U, "SOSV", "Extremophile microorganisms for agricultural biologics", "Industrial Biotech, Food/Nutrition", U, "VC-portfolio (SOSV)"),
    ("Hoofprint Biome", U, "US", U, "Seed", U, U, "SOSV", "Methane suppression via biotech", "Industrial Biotech, Bioprocessing", U, "VC-portfolio (SOSV)"),
    ("Flying Embers", "flyingembers.com", U, U, U, U, U, "Ecosystem Integrity Fund", "Probiotic fermentation for beverages", "Fermentation, Food/Nutrition", U, "VC-portfolio (Ecosystem Integrity Fund)"),
    ("SANA Foods", "sanafoods.com", U, U, U, U, U, "Ecosystem Integrity Fund", "Organic packaged foods", "Food/Nutrition", U, "VC-portfolio (Ecosystem Integrity Fund)"),
    ("Mosa Meat", U, "Netherlands", U, U, U, U, "M Ventures", "Cultivated meat biotech", "Food/Nutrition, Bioprocessing", U, "VC-portfolio (M Ventures)"),
    ("Cyto-Facto", U, U, U, U, U, U, "Asahi Kasei Ventures", "Cell and gene therapy manufacturing", "Bioprocessing, Synthetic Biology", U, "VC-portfolio (Asahi Kasei Ventures)"),
    ("iVexSol", U, U, U, U, U, U, "Asahi Kasei Ventures", "Lentiviral vectors for CGT manufacturing", "Bioprocessing, Synthetic Biology", U, "VC-portfolio (Asahi Kasei Ventures)"),
    ("Syngoi", U, U, U, U, U, U, "Asahi Kasei Ventures", "Synthetic DNA for gene therapies", "Synthetic Biology, Bioprocessing", U, "VC-portfolio (Asahi Kasei Ventures)"),
    ("Exactmer", U, U, U, U, U, U, "Asahi Kasei Ventures", "Polymeric pharmaceuticals", "Specialty Chemicals", U, "VC-portfolio (Asahi Kasei Ventures)"),
    ("NFW Technologies", U, U, U, U, U, U, "Asahi Kasei Ventures", "Plastic-free performance materials", "Advanced Materials", U, "VC-portfolio (Asahi Kasei Ventures)"),
    ("Multus", U, U, U, U, U, U, "Asahi Kasei Ventures", "Growth media for cellular agriculture", "Bioprocessing, Food/Nutrition", U, "VC-portfolio (Asahi Kasei Ventures)"),
]
