# Icos-fit scores collected from Opus scoring batches 1-15
# name -> (score, rationale, question)
SCORES = {
    # batch 1
    "Rebus Biosystems": (4, "Ambiguous identity (fermentation competitor of pow.bio vs. spatial-genomics namesake), no clear food/chem or LP fit and thin traction", "Is this actually a continuous-fermentation biomanufacturing platform, and who are its industrial B2B customers?"),
    "Unibio": (7, "Methane-to-protein single-cell protein via proprietary U-Loop fermentation; B2B feed/food, EU-based (Denmark), climate angle, strong Bühler/FrieslandCampina relevance, but late-stage scale-up risk", "What are the CAPEX/unit economics of gas fermentation at commercial scale and are offtake contracts secured?"),
    "Debut Biotech": (7, "Cell-free biomanufacturing of high-value food/cosmetic ingredients; clear B2B, defensible platform, LP-relevant (food/nutrition), though US-based with moderate EU relevance", "Does the cell-free approach hold margin and scalability advantages over cell-based fermentation competitors?"),
    "Sustainable Bioproducts": (5, "Fungal fermentation protein is food/nutrition-relevant, but company is a consumer CPG brand (B2C tilt), US-only, limited EU presence and thin B2B/LP synergy", "Is there a genuine B2B ingredient offering, or is the model primarily a consumer-facing food brand?"),
    "Motif Ingredients": (5, "B2B food-ingredient platform (Ginkgo-derived, defensible) with LP relevance, but wound-down/IP-sold status is a negative why-now and it is US-based", "What is the current operating and IP-ownership status of the business?"),
    "Cauldron Ferm": (8, "Direct mandate match: proprietary continuous hyper-fermentation, fresh Series A2 (2025) why-now, B2B precision-fermentation platform relevant to food and specialty-chem LPs; main gap is non-EU (Australia) geography", "Is the hyper-fermentation titer/productivity advantage independently validated and protected by patents?"),
    # batch 2
    "Liberation Bioindustries": (6, "Recent $60M Series A fermentation biomanufacturing fits industrial-biotech LPs (Nouryon/FrieslandCampina), but US/Saudi footprint has no EU presence and the end-application/product is vague", "What specific molecules/products will the US and Saudi facilities produce, and are there committed offtake customers versus speculative capacity?"),
    "C16 Biosciences": (7, "Precision-fermentation palm oil alternative maps directly onto specialty-chemicals and food/nutrition LPs with a defensible platform and deforestation/climate angle; only its lone 2020 Series A looks stale", "Is the technology at cost parity with conventional palm oil at commercial scale, and what has been raised/shipped since the 2020 round?"),
    "Sennos": (7, "AI-driven real-time fermentation sensing/control squarely hits the industry-AI + industrial-biotech thesis with strong traction ($50M+ raised) and clear B2B/Bühler relevance; weakness is US-only, no EU base", "What is the recurring-revenue mix and net retention across brewing vs. biopharma/biofuel customers, and how defensible is the sensor+data moat?"),
    "Sable Fermentation, Inc.": (3, "Early-stage (~$1M, loan-funded) pilot-scale contract biomanufacturing service with no proprietary/defensible platform, no EU footprint and no LP relevance", "Does Sable own any differentiated IP, or is it purely a fee-for-service CDMO with no equity-grade moat?"),
    "BioNukleo": (4, "EU (Berlin/TU Berlin) enzymatic biocatalysis gives some specialty-chemicals fit and geographic relevance, but a 2014 university spin-off skewed toward pharma/fine-chemical intermediates with thin funding", "What share of revenue is industrial/food specialty chemicals versus pharma intermediates, and is there a scalable commercial product?"),
    "Fermeate": (6, "Proprietary Princeton-derived optogenetic retrofit control with a concrete why-now (60-300% yield gain) and food-adjacent backing (Ajinomoto Ventures), but only Seed stage and US-only with no EU presence", "Are the cited 60-300% output gains validated in third-party industrial fermenters at scale, and is there a paying pilot?"),
    # batch 3
    "Plantible": (7, "Food/nutrition B2B protein play with FrieslandCampina/Bühler LP fit and a fresh 2025 IFT award, but US-based and closer to plant extraction than true fermentation", "Is the RuBi protein platform genuinely continuous-fermentation-based or biomass extraction, and what is committed offtake volume?"),
    "Chitose": (4, "Fermentation heritage but Japan-only (no EU), diffuse across biopharma/jet-fuel/algae, and no clear Nouryon/Bühler/FrieslandCampina hook", "Which single fermentation vertical is commercially anchored, and is there any EU manufacturing or LP-relevant application?"),
    "Berkeley Yeast": (5, "Yeast-strain fermentation enabler with food/beverage relevance and Anterra backing, but a US university spinout at early Series A", "What paying commercial customers and production-scale deployments exist beyond the UC Berkeley IP, and is there EU relevance?"),
    "Infinite Roots": (8, "Germany-based, EIC-backed Series B mycelium protein with strong EU presence and direct FrieslandCampina/Bühler LP fit and defensible scaling tech", "What are current cost-per-kg economics versus incumbent protein and secured industrial-scale offtake agreements?"),
    "Again": (8, "CO2-to-chemicals gas-biomanufacturing hitting CCUS + specialty-chemicals theses with direct Nouryon LP relevance, EU-relevant, Series A, measurable carbon-negative claim", "What is the verified per-tonne CO2 conversion economics and product spec/purity versus fossil-derived chemical incumbents?"),
    "Pando Bioscience": (5, "Industry-AI enzyme-engineering platform, but oriented to fermentation-dependent biopharma, US-based, with weak LP relevance and unclear industrial/food pull", "Can the AI screening platform be pointed at food/specialty-chemical enzyme targets with an LP, and what is defensibility versus other enzyme-ML players?"),
    # batch 4
    "Differential Bio GmbH": (8, "German B2B play combining industry-AI + microbial fermentation, on-thesis for the continuous-fermentation mandate with strong Bühler/Nouryon relevance and clear EU presence; only drag is accelerator-stage/early traction", "What paying customers or process-development contracts validate the automation platform beyond accelerator/pilot stage?"),
    "Lygos": (7, "Proprietary microbial-engineering B2B producing specialty/industrial chemicals from sugars (strong Nouryon fit) fits the fermentation mandate, docked mainly for US-only footprint and weak EU nexus", "Does Lygos have any EU manufacturing, partnership, or go-to-market presence relevant to the LP base?"),
    "Avantium": (3, "Excellent thematic fit (Dutch specialty chemicals/advanced materials, Nouryon-relevant) but a publicly-listed established company, failing the Series A/B stage mandate outright", "Is there any Series A/B-shaped vehicle (spinout, project SPV, private round) rather than the listed parent, or is this simply out of stage?"),
    "GFBiochemicals": (6, "EU (Italy) B2B biochemical/levulinic-acid producer with Nouryon-relevant specialty-chemical output, but no concrete why-now signal and fermentation/continuous-process fit is unclear", "Is production based on continuous fermentation, and what is current commercial traction and financing stage?"),
    "Micropep Technologies": (5, "French agri-biotech (peptides for crop protection) with EU presence and food/agri adjacency, but weak LP fit, no why-now signal, and unclear alignment to the continuous-fermentation mandate", "Are the micropeptides produced via scalable (continuous) fermentation, and which LP's value chain does the product actually touch?"),
    "P2 Science": (6, "B2B green-chemistry specialty ingredients from renewable feedstocks (Nouryon/BASF-relevant, continuous-flow process) but it is chemical synthesis rather than fermentation, US-based", "Is the core process fermentation-based or purely catalytic flow chemistry, and does the B2B ingredient portfolio map to an LP's demand?"),
    # batch 5
    "Verley": (8, "Precision-fermentation dairy proteins (ex-Bon Vivant), French B2B ingredients firm directly relevant to FrieslandCampina and Bühler, strong fermentation-mandate fit and why-now in dairy-alternative scaling", "Is the continuous/precision fermentation process cost-competitive at commercial scale, and are there regulatory approvals in the EU?"),
    "VEGDOG": (2, "Vegan pet food is pure B2C/DTC with no industrial process, no defensible proprietary tech, and no meaningful strategic-LP relevance", "Is there any B2B/ingredient-licensing angle, or is this exclusively a consumer brand play?"),
    "Genomines": (5, "Phytomining (nickel from plants) is a genuinely novel industrial-biotech/critical-materials play with EU base and Nouryon adjacency, but early-stage with thin commercial traction and no fermentation fit", "What is the demonstrated metal yield/economics vs. conventional mining, and is there any offtake or pilot at industrial scale?"),
    "Isobionics": (8, "Continuous fermentation of flavor/fragrance ingredients is a textbook B2B specialty-chemicals + food/nutrition fit with strong Nouryon/FrieslandCampina relevance and EU (NL) presence", "Is the company investable given it is already owned by DSM-Firmenich, or is this effectively exited?"),
    "Incredosugar": (7, "Fiber-based sugar-reduction food ingredient with clear B2B model relevant to Bühler and FrieslandCampina and a strong why-now in sugar-reduction regulation, though not a fermentation platform", "How defensible is the IP and what is the ingredient's proven functionality/cost at scale with major food OEMs in the EU?"),
    "Planetary": (5, "Bioreactor infrastructure for ocean alkalinity enhancement gives a measurable CO2-removal claim and CCUS-thesis relevance with EU (CH) base, but revenue model relies on carbon-credit markets, LP relevance is weak", "What is the durable revenue model beyond voluntary carbon credits, and what is MRV/permitting status for ocean-based CDR?"),
    # batch 6
    "Switch Bioworks": (4, "Stanford synbio nitrogen-fixing biofertilizer with a carbon-neutral climate angle, but Seed stage (below A/B mandate), US-only with no EU footprint, and only loose LP relevance", "Is there a defined path to a Series A and any EU commercial/production presence?"),
    "Reshape": (7, "Copenhagen-based Astanor-backed Series A (~$20M) B2B industry-AI/robotics platform automating biotech/food/ag R&D, strong EU presence and relevance to Bühler/FrieslandCampina/Nouryon lab workflows", "What is recurring revenue vs. hardware-sale mix, and is there validated pull from industrial food/chem customers rather than academic labs?"),
    "Zya": (6, "UK B2B food-enzyme (Convero sugar-to-fibre) squarely in food/nutrition thesis with direct FrieslandCampina/Bühler relevance and a GLP-1/sugar-reduction why-now, but only ~$5M raised (early, below clean A/B)", "Are there signed CPG offtake/co-development deals and regulatory clearance to support the 2026 US launch?"),
    "Amplifye": (5, "Computational protein-design enzyme platform with food/feed/aquaculture applications relevant to FrieslandCampina, real Series A ($18.4M), but flagship go-to-market is a B2C protein supplement and it is US-only", "Is the near-term revenue model B2C supplement or licensable B2B ingredient platform?"),
    "Obulytix": (2, "Belgian phage-lysin enzyme platform is EU-based but is therapeutics/antibiotics-ONLY with no industrial or food application, no strategic-LP relevance", "Does any non-therapeutic (food-safety/industrial antimicrobial) application exist that would create Nouryon/FrieslandCampina relevance?"),
    "Arevo": (5, "Swedish (strong EU) B2B arginine-based biostimulant with defensible IP, a recent EUR7.3M raise and a nitrogen-emissions climate plus, but plant-nutrition/agtech only with loose LP fit and no fermentation angle", "What is the commercial traction beyond forestry nurseries to justify Series A/B fit?"),
    # batch 7
    "Avenue Biosciences": (4, "AI-driven protein-engineering platform (industry-AI angle) but seed-stage University of Helsinki spinout skewed to therapeutic-protein manufacturing, thin traction and no clear LP hook", "Does the secretory-pathway platform have a validated food/industrial precision-fermentation application, and what non-biologics revenue exists?"),
    "Cellfion": (4, "PFAS-free bio-based membranes fit advanced-materials thesis and loosely touch Nouryon, but grant/seed-stage spinout in energy-storage/battery-adjacent materials with minimal traction", "Is there any commercial offtake or paying industrial customer beyond grants, and does the membrane address a fermentation/specialty-chemical use case rather than batteries?"),
    "ArgusEye": (6, "Patented LSPR real-time bioprocess/fermentation monitoring (industry-AI + bioprocessing), Swedish/EU, fresh Apr-2026 EUR3.3M raise, application-agnostic sensing relevant to food and industrial fermentation LPs", "Beyond biopharma, is the sensor validated on food/industrial fermentation lines, and is the round a true Series A with recurring revenue?"),
    "Evodia": (8, "Precision-fermentation natural aromas squarely in food/nutrition thesis, strong B2B traction (70+ brews, top-40 breweries), patented tech, EU (Copenhagen), Dec-2025 EUR6M raise, direct Bühler and FrieslandCampina relevance", "Are current brewery engagements converting to volume supply contracts, and can the yeast platform scale to continuous fermentation economics?"),
    "Ironic Biotech": (5, "Precision-fermentation iron-rich plant proteins fit food/nutrition thesis with FrieslandCampina/Bühler relevance and a climate-footprint plus, but pre-seed EUR1M spinout with thin traction", "What is the technology readiness/scale-up status and regulatory pathway, and is there any pilot offtake beyond lab-scale proof?"),
    "Provivi": (5, "Pheromone-biosynthesis biopesticides fit specialty-chemicals/industrial-biotech thesis with defensible tech and Syngenta partnership, but Series C stage is well past the A/B mandate, US-based, BASF-backed not Icos", "Given late stage and US base, is there a Series A/B-appropriate EU entry point or industrial-fermentation angle mapping to Nouryon?"),
    # batch 8
    "BigRep GmbH": (4, "Advanced-materials/3D-printing with strong EU (Germany) B2B footprint, but established/late-stage (not Series A/B) and weak fit to any strategic LP", "What is the current funding stage and is there any near-term round consistent with ICF's Series A/B window?"),
    "Phomera": (4, "Advanced-materials play with BASF backing implying specialty-chemicals adjacency, but near-zero disclosed detail on stage, geography, or defensibility", "What is the specific technology/product, funding stage, and HQ geography, and how does it map to Nouryon's specialty-chemicals mandate?"),
    "Pearl Bio": (6, "Proprietary cell-free protein platform yielding biomaterials fits advanced-materials/specialty-chemicals with clear B2B and defensible IP, though US-based Growth stage (beyond A/B) with only indirect LP relevance", "Which commercial biomaterial applications are furthest along, and do any map to a Nouryon or FrieslandCampina use case?"),
    "BiomEdit": (5, "Microbiome-based livestock/animal-health products are food/nutrition-value-chain adjacent with proprietary biotech, but US-based and skews animal-health with limited industrial/chemicals pull", "Are the products classified as therapeutics/veterinary drugs or as feed/nutrition inputs, and which strategic LP would sponsor?"),
    "Industrial Microbes Inc.": (7, "Engineered-microbe gas/methane fermentation to chemicals hits specialty-chemicals (Nouryon LP) plus a genuine industrial-climate/CO2-mitigation angle with defensible platform and clear B2B, on-mandate fermentation", "What is the demonstrated commercial traction/scale-up milestone and unit economics, and is there an EU deployment or Nouryon partnership pathway?"),
    "Green Culture Inc.": (5, "Controlled-environment-agriculture/plant-factory tech fits food/nutrition with loose Bühler relevance, but Japan-only geography, no EU relevance, and off-mandate (not fermentation) with uncertain defensibility", "What is proprietary/defensible in the cultivation platform versus commodity CEA, and is there any EU market or strategic-LP entry path?"),
    # batch 9
    "bitBiome Inc.": (7, "B2B microbial-genomics strain-discovery platform squarely fits industrial biotech/fermentation mandate with defensible IP and Nouryon specialty-chem relevance; JP presence is a plus", "What paying commercial/co-development contracts exist, and does the platform deliver production strains for continuous fermentation vs. only discovery?"),
    "CellFiber Co., Ltd.": (6, "B2B hydrogel-microfiber bioprocessing tooling for mass cell culture fits advanced-materials/bioprocessing thesis with defensible tech, but LP fit is indirect and traction is scaling-stage", "What is annualized revenue and how many industrial bioproduction customers use the fiber at commercial scale?"),
    "JEPLAN Inc.": (7, "Proven B2B PET/textile chemical-recycling with operating plants gives strong specialty-chemicals (Nouryon) and circular/industrial-climate fit, but likely past Series A/B stage and outside the fermentation mandate", "Is current financing stage/valuation still within ICF's Series A/B entry window, and what are unit economics vs. virgin PET?"),
    "EF Polymer K.K.": (5, "B2B biodegradable super-absorbent polymer from food/veg waste fits advanced-materials with food-waste upcycling adjacency, but LP relevance and defensibility are moderate", "What is proprietary IP protection and gross margin at scale versus incumbent synthetic SAPs?"),
    "Polyuse Inc.": (3, "3D-printing construction polymers sit outside core thesis sectors with no clear Nouryon/Bühler/FrieslandCampina LP relevance despite a B2B model", "Is there any specialty-chemicals or food/industrial-biotech angle that would create LP relevance beyond construction?"),
    "Umami Bioworks": (5, "Cell-based cultivated-seafood platform gives FrieslandCampina/Bühler food-nutrition relevance and B2B licensing model, but Singapore geography, non-fermentation cultivation, regulatory/capital intensity, and B2C-proximity weaken fit", "What is the regulatory approval and cost-parity pathway, and is revenue from B2B tech licensing already contracted?"),
    # batch 10
    "JALA Tech": (2, "Aquaculture/shrimp marketplace is B2C-adjacent platform software with weak defensibility and no clear specialty-chem/materials/CCUS or strategic-LP fit", "Is there any proprietary industrial process IP, or is this purely a farmer-facing marketplace/SaaS with no continuous-fermentation angle?"),
    "Austrianova": (5, "Cell/bacteria encapsulation is defensible and could support immobilized-cell industrial fermentation, but historical focus is therapeutics, pulling it toward the pharma-only penalty", "What share of pipeline/revenue is industrial biotech versus cancer/therapeutic licensing?"),
    "Accelerated Materials": (8, "AI-driven nanomaterial synthesis squarely hits advanced-materials + industry-AI thesis with a B2B platform and clear Nouryon relevance; Singapore counts as a geography plus here", "Is the AI/synthesis platform proprietary and moat-defensible, and are there paying specialty-chemical/materials customers validating it?"),
    "GRA&GREEN": (6, "Genome-edited crop development gives real food/nutrition relevance and defensible IP, but as a university spinout it risks the thin-traction early-spinout penalty", "What commercial traction exists beyond the academic founding, and does it touch Bühler/FrieslandCampina value chains?"),
    "Symbiobe": (5, "Marine photosynthetic-organism biomass has CCUS/circular-economy and bio-materials relevance, but it's an early university-type spinout with likely thin traction", "Is the photosynthetic cultivation continuous and scaled beyond lab, and what is the unit-economics/product offtake evidence?"),
    "Rhinoflux": (6, "Bioenergy carbon capture (BECCS) directly maps to the CCUS/industrial-climate thesis with a strong why-now and Nouryon-adjacent industrial relevance, but plant-scale proof is unproven", "Does Rhinoflux own defensible capture technology or just integrate BECCS plants, and is there an operating/pilot facility with validated capture cost?"),
    # batch 11
    "The Ethical Spirits & Co.": (3, "Circular distillery upcycling fermentation byproducts, but predominantly a B2C consumer spirits brand with limited defensible tech and weak LP fit", "Is there a licensable B2B upcycling/ingredient platform separable from the consumer spirits brand?"),
    "Aqua Theon": (4, "Seaweed food/biotech touches FrieslandCampina/Bühler adjacency, but tech description is vague with no evident proprietary platform or traction", "What is the specific defensible technology and is there any commercial off-take or B2B ingredient revenue today?"),
    "Sirrus": (7, "Proprietary methylene malonate monomer platform for adhesives/coatings is a strong B2B specialty-chemicals fit with direct Nouryon relevance", "How defensible is the monomer IP/manufacturing at scale, and what is current production capacity and design-in traction with formulators?"),
    "Visolis": (9, "Continuous-fermentation synbio for carbon-negative mevalonate-based materials/chemicals hits fermentation mandate, CCUS/climate, advanced materials, and Nouryon fit with clear why-now", "What are unit economics and titer/rate/yield at commercial scale, and is offtake/EU market access secured?"),
    "Amide": (5, "Automated peptide/protein synthesis is a defensible B2B industrial-biotech tooling platform, but leans pharma-adjacent with thin food/chemicals LP relevance", "Beyond pharma, what industrial/food-ingredient applications and customers validate the non-therapeutic thesis?"),
    "Kano": (2, "Precision genomic editing platform reads as therapeutics/pharma-only, early-stage, with no clear industrial/food application or LP relevance", "Is there any non-therapeutic industrial or agri/food-bio application and commercial traction?"),
    # batch 12
    "Foray Bioscience": (2, "Ecosystem-restoration plant cell biotech sits off-thesis with no clear food/chem/materials LP fit and reads as an early spinout lacking commercial traction", "What paying commercial revenue exists today and which thesis sector does it actually serve?"),
    "Tierra Biosciences": (6, "Cell-free synbio protein-manufacturing platform is proprietary and B2B with real food/nutrition and specialty-chem relevance, though US-based and not fermentation per se", "Can the cell-free platform scale economically to industrial food/chemical protein volumes, with a committed paying B2B customer pipeline?"),
    "6K Inc": (7, "Proprietary microwave-plasma advanced-materials production is strongly on-thesis and B2B with Nouryon/industrial relevance, but likely past Series A/B stage", "What is the current financing stage and round size, and does it still fit Icos's Series A/B mandate?"),
    "Mattiq": (7, "Industry-AI plus advanced-materials/catalyst discovery hits two thesis sectors with clear Nouryon specialty-chemicals relevance and defensible high-throughput IP", "Does the AI discovery engine yield validated, IP-protected materials with paying customers?"),
    "Huue": (6, "Fermentation-derived indigo is a defensible bio-based specialty chemical with clear Nouryon relevance and a strong sustainability why-now, but niche textile market and unproven scale", "What is cost/scale parity of biosynthetic indigo versus petrochemical, and are there committed textile-industry offtake agreements?"),
    "Talus Renewables": (6, "Modular green ammonia spans specialty chemicals and industrial-climate with EU decarbonization relevance and B2B model, but fertilizer/agri LP fit is indirect", "Is the modular unit protected IP or mainly systems integration, and what are unit economics versus grey ammonia?"),
}
SCORES.update({
    # batch 13
    "ForeLight": (6, "B2B natural food colors/omega-3 via patented photosynthetic bioreactor fits food/nutrition thesis and why-now synthetic-dye bans, with Bühler/FrieslandCampina relevance, but US-only, thin traction and sub-Series-A scale", "Is there recurring commercial ingredient revenue and a path to EU market entry, or is this still pre-scale after 15 years?"),
    "Mara Renewables": (8, "Precision-fermented algal omega-3 DHA with real commercial traction (Nestlé, M&S), UK production giving EU relevance, patented fermentation matching the mandate, and direct FrieslandCampina nutrition/infant-formula fit", "What are gross margins and cost-per-kg DHA versus incumbent fish-oil and DSM algal-oil, and how defensible is the strain/process IP at scale?"),
    "Aspect Biosystems": (2, "3D bioprinting for therapeutic tissues (Novo Nordisk-type pharma deals) is therapeutics-only with no food/industrial application, no LP relevance, and no fermentation angle", "Is there any non-pharma industrial or food-manufacturing use case that would bring it into the ICF mandate?"),
    "Correlia Biosystems": (2, "Spinout selling microscale proteomic/immunoassay tools for biopharma analytics — no industrial/food application, no LP relevance, hits the excluded early university-spinout profile", "Does any customer segment outside biopharma R&D generate material revenue that maps to an ICF thesis sector?"),
    "Biodel AG": (5, "US industrial-biotech biologicals for soil reclamation/carbon sequestration touch industrial-climate and specialty-chemicals themes with patented processes, but ag-biologicals link to Nouryon is loose and EU presence is absent", "Is the carbon-sequestration/soil claim independently validated and does the product line have a defined EU or Nouryon-adjacent route?"),
    "NewLeaf Symbiotics": (6, "Fermentation-produced M-troph biologicals for specialty chemicals/agriculture fit the specialty-chemicals thesis with clearest Nouryon LP relevance and B2B commercial traction, but US-centric with limited EU footprint", "What is the specialty-chemicals revenue split, and is there an EU commercial or partnership beachhead relevant to Nouryon?"),
    # batch 14
    "Membrion": (7, "Proprietary ceramic membranes for specialty-chem/bioprocessing separations, clear B2B, direct Nouryon relevance; US HQ limits EU proximity", "What proprietary IP protects the ceramic membrane process, and what is current commercial revenue/traction with EU chemical customers?"),
    "Brightly": (3, "Thin specialty-chemicals description reads as B2C clean-label consumer products with no evident defensible tech or LP linkage", "Is the actual model B2B ingredient/chemical supply or B2C branded product, and what proprietary technology underpins it?"),
    "Blue Nalu": (4, "Cultivated seafood touches food/nutrition but is capital-heavy, regulation-gated, effectively B2C end-product with weak fit to dairy/grain/chemicals LPs; US-based", "What is the near-term regulatory approval path and unit-economics roadmap, and does any LP have a credible processing/ingredient tie-in?"),
    "Puna Bio": (3, "Extremophile ag-biologics is thesis-adjacent but Seed-stage and Argentina/US with no EU presence, hitting the university-spinout/early-traction exclusion", "What paid commercial field traction and EU regulatory/market entry plan exists?"),
    "Mosa Meat": (6, "Netherlands/EU cultivated-meat with strong food/nutrition thesis and Bühler/FrieslandCampina relevance, but capital-intensive, regulation-bound, and end-product B2C rather than continuous-fermentation B2B tooling", "What is the EU novel-food approval timeline and path to cost parity, and is there a B2B ingredient/process-licensing angle?"),
    "iVexSol": (1, "Lentiviral vectors for cell & gene therapy manufacturing is pharma-only tooling with no industrial/food application and no LP relevance", "Is there any credible non-pharma industrial or food-bioprocessing application, or does this fall entirely outside the mandate?"),
    # batch 15
    "Exactmer": (5, "Proprietary Nanostar Sieving (OSN membrane) precision-polymer platform with strong EU presence and defensible tech, but positioned pharma/oligo-only, weakening industrial specialty-chem applicability", "Does the platform have validated non-pharma specialty-chemicals applications, or is the addressable market effectively oligonucleotide therapeutics only?"),
    "NFW Technologies": (6, "Core advanced-materials/industrial-climate fit with proprietary plastic-free bio-based platform sold B2B, but US-centric, consumer-fashion end market, and already past an $85M Series B", "Given the 2022 $85M Series B and US/fashion focus, what is the current stage and is there a defensible, EU-relevant B2B path?"),
})
print(f"Total scores: {len(SCORES)}")
